chore: configure git hooks

diff --git a/.githooks/pre-commit b/.githooks/pre-commit
--- a/.githooks/pre-commit
+++ b/.githooks/pre-commit
@@ -1,58 +1,59 @@
-#!/usr/bin/env bash
-echo "pre commit hook start"
+#!/bin/bash
 
-# Making this more flexible. Whatever this script finds in the bin, it will use.
-CHANGED_PHP_FILES=$(git diff --cached --name-only --diff-filter=ACM -- '*.php')
-if [ -n "$CHANGED_PHP_FILES" ]; then
-  ECS="./vendor/bin/ecs"
-  PHP_CS_FIXER="./vendor/bin/php-cs-fixer"
-  PHPSTAN="./vendor/bin/phpstan"
+# Colors
+RED='\033[0;31m'
+GREEN='\033[0;32m'
+YELLOW='\033[0;33m'
+NC='\033[0m' # No Color
+
+printf "Committing as ${YELLOW}$(git config user.name) ${NC}/ ${YELLOW}$(git config user.email)${NC}\n"
+
+PASS=true
+
+CHANGED_FILES=$(git diff --cached --name-only --diff-filter=ACM -- '*.php')
+
+# early return
+if [[ -z "$CHANGED_FILES" ]]; then
+  # printf "${YELLOW}No .php files in this commit${NC}\n"
+  exit 0;
 fi
 
-CHANGED_JSON_FILES=$(git diff --cached --name-only --diff-filter=ACM -- '*.json')
-if [ -n "$CHANGED_JSON_FILES" ]; then
-  JSONLINT="./vendor/bin/php-cs-fixer"
-  VALIDATE_JSON="./vendor/bin/php-cs-fixer"
-fi
+printf "Running pre commit hook\n"
 
-CHANGED_YAML_FILES=$(git diff --cached --name-only --diff-filter=ACM -- '*.ya?ml')
-if [ -n "$CHANGED_YAML_FILES" ]; then
-  YAML_LINT="ecs.php"
-fi
-
-CHANGED_CSS_FILES=$(git diff --cached --name-only --diff-filter=ACM -- '*.css')
-if [ -n "$CHANGED_CSS_FILES" ]; then
-  CSS_LINT="ecs.php"
-fi
-
-CHANGED_SASS_FILES=$(git diff --cached --name-only --diff-filter=ACM -- '*.scss')
-if [ -n "$CHANGED_SASS_FILES" ]; then
-  SASS_LINT="ecs.php"
-fi
-
-CHANGED_JS_FILES=$(git diff --cached --name-only --diff-filter=ACM -- '*.(j|t)sx?')
-if [ -n "$CHANGED_JS_FILES" ]; then
-  JSLINT="ecs.php"
-  JSHINT="ecs.php"
-fi
-
-CHANGED_PHP_FILES=$(git diff --cached --name-only --diff-filter=ACM -- '*.php')
-
-
-    echo "php-cs-fixer start"
-    $ECS fix --config "$PHP_CS_CONFIG" $CHANGED_FILES;
-    echo "php-cs-fixer finish"
-
-    echo "php-stan start"
-
-    if $PHP_STAN analyse -c ./phpstan.neon --memory-limit=512M $CHANGED_FILES; then
-      echo 'php-stan finish'
+# ecs
+PHP_ECS="./vendor/bin/ecs"
+if ([ -x $PHP_ECS ] && [ -n "$CHANGED_FILES"]); then
+    printf "ECS start"
+    $PHP_ECS check ${CHANGED_FILES} --fix
+    if [[ "$?" == 0 ]]; then
+        # Add the fixed files back to the staging area
+        printf "${GREEN}ECS passed${NC}\n"
+        if [[ ! -z "$CHANGED_FILES" ]]; then
+          git add "${CHANGED_FILES}"
+        fi
     else
-      echo 'php-stan found some errors'
-      exit 1;
+        PASS=false # Different code than 0 means that there were unresolved fixes
     fi
+else
+    printf "${YELLOW}ECS missing or no .php changes made${NC}\n"
+fi
 
-    git add $CHANGED_FILES;
+# phpstan
+PHP_STAN="./vendor/bin/phpstan"
+if ([ -x $PHP_STAN ] && [ -n "$CHANGED_FILES" ]); then
+    printf "PHPStan start"
+    if $PHP_STAN analyse --memory-limit=1G $CHANGED_FILES; then
+      # All good
+      printf "${GREEN}PHPStan passed${NC}\n"
+    else
+      PASS=false
+    fi
+fi
 
-
-echo "pre commit hook finish"
+if ! $PASS; then
+  printf "pre commit hook ${RED}FAILED${NC}\n"
+  exit 1
+else
+  printf "pre commit hook ${GREEN}SUCCEEDED${NC}\n"
+  exit 0
+fi
